from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from .change_impact import build_change_impact, render_change_impact_markdown
from .graph import build_dependency_graph, render_dot
from .planner import build_change_plan, render_migration_plan
from .routes import (
    discover_visual_targets,
    render_playwright_config,
    render_playwright_spec,
    render_visual_regression_markdown,
)
from .semantic import build_semantic_system, render_theme_css


def _escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(data: dict[str, Any]) -> str:
    summary = data["summary"]
    derived = data["derived"]
    lines = [
        "# Visual System Index", "",
        f"> Generated by **BlackMamba Visual Index v{data['meta']['version']}**", "",
        "## Project snapshot", "", "| Metric | Value |", "|---|---:|",
        f"| Files indexed | {data['meta']['file_count']} |",
        f"| Color usages | {summary['color_usage_total']} |",
        f"| Unique colors | {summary['unique_color_literals']} |",
        f"| CSS variables | {summary['css_variables_defined']} |",
        f"| Keyframes | {summary['keyframes']} |",
        f"| Motion declarations | {summary['motion_declarations']} |",
        f"| Internal dependency edges | {derived['dependency_graph']['summary']['internal_edges']} |",
        f"| Visual migration risk | {derived['change_plan']['risk']['level']} ({derived['change_plan']['risk']['score']}/100) |",
        f"| Discovered routes | {len(derived['visual_regression']['routes'])} |",
        f"| Planned captures | {derived['visual_regression']['capture_count']} |", "",
        "## Detected stack", "",
    ]
    if summary["frameworks"]:
        lines += ["| Technology | Signals |", "|---|---:|"]
        lines += [f"| {_escape(name)} | {count} |" for name, count in summary["frameworks"].items()]
    else:
        lines.append("_No known framework signatures detected._")

    lines += ["", "## Priority visual files", ""]
    if data["priority_files"]:
        lines += ["| File | Category | Roles |", "|---|---|---|"]
        for item in data["priority_files"][:250]:
            lines.append(f"| `{_escape(item['path'])}` | {item['category']} | {_escape(', '.join(item['roles']))} |")
    else:
        lines.append("_No priority files detected._")

    lines += ["", "## Dependency hotspots", "", "| File | Incoming | Outgoing | Impact |", "|---|---:|---:|---:|"]
    for item in derived["dependency_graph"]["hotspots"][:25]:
        lines.append(f"| `{_escape(item['path'])}` | {item['incoming']} | {item['outgoing']} | {item['impact_score']} |")

    all_colors = []
    for kind, entries in data["visual_system"]["colors"].items():
        all_colors.extend((entry["count"], kind, entry) for entry in entries)
    all_colors.sort(reverse=True, key=lambda item: item[0])
    lines += ["", "## Most-used colors", ""]
    if all_colors:
        lines += ["| Value | Type | Uses | Example files |", "|---|---|---:|---|"]
        for count, kind, entry in all_colors[:60]:
            examples = ", ".join(f"`{path}`" for path in entry["locations"][:3])
            lines.append(f"| `{_escape(entry['value'])}` | {kind} | {count} | {examples} |")
    else:
        lines.append("_No color literals detected._")

    lines += ["", "## Generated themes", "", "| Theme | Passed checks | Failed checks |", "|---|---:|---:|"]
    for audit in derived["semantic_system"]["accessibility"]["themes"]:
        lines.append(f"| {audit['theme']} | {audit['passed']} | {audit['failed']} |")

    lines += ["", "## Recommendations", ""]
    if data["recommendations"]:
        for item in data["recommendations"]:
            lines.append(f"- **{item['level'].upper()} — {item['title']}:** {item['detail']}")
    else:
        lines.append("- No immediate visual-system risks detected.")
    lines += [
        "", "## Generated artifacts", "",
        "- `semantic-tokens.json` — inferred token contract and theme values",
        "- `themes.css` — light, dark, BlackMamba and high-contrast CSS variables",
        "- `accessibility-audit.json` — contrast evidence",
        "- `dependency-graph.json` and `dependency-graph.dot` — impact graph",
        "- `MIGRATION_PLAN.md` — ordered rollout plan",
        "- `visual-regression-plan.json` and Playwright templates — screenshot baseline matrix",
        "- `change-impact.json` and `CHANGE_IMPACT.md` — changed-file blast radius", "",
    ]
    return "\n".join(lines)


def render_html(data: dict[str, Any]) -> str:
    summary = data["summary"]
    derived = data["derived"]
    metrics = {
        "Files": data["meta"]["file_count"],
        "Color usages": summary["color_usage_total"],
        "Unique colors": summary["unique_color_literals"],
        "CSS variables": summary["css_variables_defined"],
        "Keyframes": summary["keyframes"],
        "Graph edges": derived["dependency_graph"]["summary"]["internal_edges"],
        "Risk": f"{derived['change_plan']['risk']['score']}/100",
        "Routes": len(derived["visual_regression"]["routes"]),
        "Captures": derived["visual_regression"]["capture_count"],
    }
    metric_cards = "".join(
        f'<div class="metric"><span>{html.escape(label)}</span><strong>{html.escape(str(value))}</strong></div>'
        for label, value in metrics.items()
    )
    recommendations = "".join(
        f'<article class="rec {html.escape(item["level"])}"><b>{html.escape(item["title"])}</b>'
        f'<p>{html.escape(item["detail"])}</p></article>' for item in data["recommendations"]
    ) or "<p>No immediate risks detected.</p>"
    priority_rows = "".join(
        f'<tr><td><code>{html.escape(item["path"])}</code></td><td>{html.escape(item["category"])}</td>'
        f'<td>{html.escape(", ".join(item["roles"]))}</td></tr>' for item in data["priority_files"][:300]
    ) or '<tr><td colspan="3">No priority files detected</td></tr>'
    hotspot_rows = "".join(
        f'<tr><td><code>{html.escape(item["path"])}</code></td><td>{item["incoming"]}</td><td>{item["outgoing"]}</td><td>{item["impact_score"]}</td></tr>'
        for item in derived["dependency_graph"]["hotspots"][:40]
    ) or '<tr><td colspan="4">No internal edges detected</td></tr>'
    color_rows: list[str] = []
    for kind, entries in data["visual_system"]["colors"].items():
        for entry in entries[:30]:
            swatch = f'<i style="background:{html.escape(entry["value"])}"></i>' if kind == "hex" else ""
            color_rows.append(
                f'<tr><td>{swatch}<code>{html.escape(entry["value"])}</code></td><td>{kind}</td>'
                f'<td>{entry["count"]}</td><td>{html.escape(", ".join(entry["locations"][:3]))}</td></tr>'
            )
    theme_cards = []
    for name, tokens in derived["semantic_system"]["themes"].items():
        swatches = "".join(
            f'<i title="{html.escape(key)}" style="background:{html.escape(value)}"></i>'
            for key, value in tokens.items() if value.startswith("#")
        )
        audit = next(
            item for item in derived["semantic_system"]["accessibility"]["themes"]
            if item["theme"] == name
        )
        theme_cards.append(
            f'<article class="theme"><b>{html.escape(name)}</b><div>{swatches}</div>'
            f'<p>{audit["passed"]} passed · {audit["failed"]} failed</p></article>'
        )
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>Visual System Index</title>
<style>:root{{color-scheme:dark;--bg:#090b11;--panel:#131725;--text:#f5f7ff;--muted:#9da8c1;--line:#29314a;--accent:#2fe0b6}}
*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(circle at 18% 0,#1e1839 0,transparent 38%),var(--bg);color:var(--text);font:14px/1.55 system-ui,-apple-system,sans-serif}}
main{{width:min(1400px,94vw);margin:auto;padding:52px 0 100px}}h1{{font-size:clamp(36px,6vw,74px);line-height:.95;letter-spacing:-.05em;margin:0 0 16px}}h2{{margin-top:48px}}p{{color:var(--muted)}}.kicker{{color:var(--accent);font-weight:800;letter-spacing:.12em;text-transform:uppercase}}.grid,.recs,.themes{{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin:28px 0}}.metric,.rec,.theme{{border:1px solid var(--line);border-radius:16px;padding:18px;background:rgba(19,23,37,.8)}}.metric span{{display:block;color:var(--muted);font-size:12px;text-transform:uppercase}}.metric strong{{font-size:30px}}.rec.high{{border-color:#a94865}}.rec.medium{{border-color:#8b733d}}.scroll{{max-height:620px;overflow:auto;border-radius:16px}}table{{width:100%;border-collapse:collapse;background:rgba(19,23,37,.8)}}th,td{{padding:11px 13px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}}th{{position:sticky;top:0;background:#151a2a;color:var(--muted);font-size:12px;text-transform:uppercase}}code{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}}td i,.theme i{{display:inline-block;width:20px;height:20px;border-radius:6px;border:1px solid #ffffff44;vertical-align:-5px;margin:4px}}</style></head>
<body><main><p class="kicker">BlackMamba Visual Index v{html.escape(data['meta']['version'])}</p><h1>Visual system<br>control map.</h1>
<p>Generated {html.escape(data['meta']['generated_at'])} · <code>{html.escape(data['meta']['project_root'])}</code></p>
<div class="grid">{metric_cards}</div><h2>Generated themes</h2><div class="themes">{''.join(theme_cards)}</div>
<h2>Recommendations</h2><div class="recs">{recommendations}</div>
<h2>Dependency hotspots</h2><div class="scroll"><table><thead><tr><th>File</th><th>Incoming</th><th>Outgoing</th><th>Impact</th></tr></thead><tbody>{hotspot_rows}</tbody></table></div>
<h2>Priority visual files</h2><div class="scroll"><table><thead><tr><th>File</th><th>Category</th><th>Roles</th></tr></thead><tbody>{priority_rows}</tbody></table></div>
<h2>Color inventory</h2><div class="scroll"><table><thead><tr><th>Value</th><th>Type</th><th>Uses</th><th>Files</th></tr></thead><tbody>{''.join(color_rows) or '<tr><td colspan="4">No colors detected</td></tr>'}</tbody></table></div>
</main></body></html>"""


def write_reports(data: dict[str, Any], output: Path, changed_paths: list[str] | None = None) -> None:
    semantic = build_semantic_system(data)
    graph = build_dependency_graph(data)
    plan = build_change_plan(data, semantic, graph)
    visual_regression = discover_visual_targets(data, semantic)
    change_impact = build_change_impact(data, graph, changed_paths or [])
    data["derived"] = {
        "semantic_system": semantic,
        "dependency_graph": graph,
        "change_plan": plan,
        "visual_regression": visual_regression,
        "change_impact": change_impact,
    }

    output.mkdir(parents=True, exist_ok=True)
    (output / "visual-index.json").write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    (output / "VISUAL_INDEX.md").write_text(render_markdown(data), encoding="utf-8")
    (output / "visual-index.html").write_text(render_html(data), encoding="utf-8")
    (output / "semantic-tokens.json").write_text(json.dumps(semantic, indent=2, ensure_ascii=False), encoding="utf-8")
    (output / "themes.css").write_text(render_theme_css(semantic), encoding="utf-8")
    (output / "accessibility-audit.json").write_text(json.dumps(semantic["accessibility"], indent=2), encoding="utf-8")
    (output / "dependency-graph.json").write_text(json.dumps(graph, indent=2, ensure_ascii=False), encoding="utf-8")
    (output / "dependency-graph.dot").write_text(render_dot(graph), encoding="utf-8")
    (output / "MIGRATION_PLAN.md").write_text(render_migration_plan(plan), encoding="utf-8")
    (output / "visual-regression-plan.json").write_text(json.dumps(visual_regression, indent=2, ensure_ascii=False), encoding="utf-8")
    (output / "visual-regression.spec.ts").write_text(render_playwright_spec(visual_regression), encoding="utf-8")
    (output / "playwright.visual.config.ts").write_text(render_playwright_config(visual_regression), encoding="utf-8")
    (output / "VISUAL_REGRESSION.md").write_text(render_visual_regression_markdown(visual_regression), encoding="utf-8")
    (output / "change-impact.json").write_text(json.dumps(change_impact, indent=2, ensure_ascii=False), encoding="utf-8")
    (output / "CHANGE_IMPACT.md").write_text(render_change_impact_markdown(change_impact), encoding="utf-8")
